name: Tests

on:
  # workflow_run:
  #   workflows: ['Lint']
  #   types:
  #     - completed

jobs:
  tests:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    container:
      image: paweumiel/devops-nuxt-frontend-prod:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: npm run test
